import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Admin Baba",
  description: "Generated by Admin Baba",
};

export default function AdminLayout({ children }) {
  return (
    <>
      <div className="py-4 w-full mx-auto xl:max-w-7xl lg:max-w-5xl md:max-w-3xl bg-gray-900 text-white rounded-b-2xl flex px-4 items-center relative">
        <Link className="grow-0 mr-auto" href={'/admin'}>
          <Image src={"/next.svg"} priority className="w-auto lg:h-8 md:h-6 h-5" alt={'Uncovered Vibes Logo'} width={158} height={32} />
        </Link>
        <div className="grow">
        </div>
        <div className="grow-0 flex gap-4">
          <Link className="font-semibold py-1 px-4 rounded-md bg-white/5" href={'/admin/post'}>Posts</Link>
          <Link className="font-semibold py-1 px-4 rounded-md bg-white/5" href={'/admin/post/add'}>Add Post</Link>
          <Link className="font-semibold py-1 px-4 rounded-md bg-white/5" href={'/admin/category'}>Categories</Link>
          <Link className="font-semibold py-1 px-4 rounded-md bg-white/5" href={'/admin/category/add'}>Add Category</Link>
        </div>
      </div>
      <main className="flex flex-col grow py-8 max-md:p-4 w-full mx-auto xl:max-w-7xl lg:max-w-5xl md:max-w-3xl">
        {children}
      </main>
    </>
  );
}
